version: "3.7"
services:
    webqa:
        restart: always
        image: ludwin/web-granja:54a0db61475131fbce71e6a20311e01a1bc70889
        ports:
            - ${WEB_PORT}:80
        environment:
            - DOCKER_SERVICE_API=http://api:${API_PORT}
        depends_on:
            - apiqa

    apiqa:
        restart: always
        image: ludwin/api-granja
        ports:
            - ${API_PORT}:${API_PORT}
        # command: npm run start:dev
        env_file:
            - .env
        depends_on:
            - databaseqa

    databaseqa:
        image: postgres:17.5-alpine
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            TZ: 'America/Guatemala'
        ports:
            - ${DB_LISTEN_PORT_OUT}:${DB_PORT}
        volumes:
            - ./tools/postgres/data:/var/lib/postgresql/data
            - ./tools/postgres/backups:/backups